baseURL = 'https://aleksandrspiridonov.github.io/lebedev/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Евгений Лебедев'
theme = 'hugo-book'
publishDir = "docs"

[caches]
  [caches.images]
    dir = ':cacheDir/images'