baseURL = 'https://evglebedev.ru/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Евгений Лебедев'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Сайт поэта Евгения Лебедева. Автор сборника 'Ошибки молодости'"
  author = "Евгений Лебедев"
  keywords = ["Евгений Лебедев", "поэзия", "стихи", "Ошибки молодости", "современная поэзия", "литература"]
  images = ["/images/og-image.jpg"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[build]
  writeStats = true
  noJSBundleInAssets = true

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Сборники"
    url = "/docs/collection/"
    weight = 2
  
  [[menu.main]]
    name = "Посты"
    url = "/posts/"
    weight = 3